[package]
name = "executor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
application = { workspace = true }
domain = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
wasmtime = { workspace = true }

[dev-dependencies]
application = { workspace = true }
artifacts = { workspace = true }
catalog = { workspace = true }
criterion = { workspace = true }
domain = { workspace = true }
runtime = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wat = { workspace = true }

[[bench]]
name = "precompile"
harness = false
