[package]
name = "artifacts"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
application = { workspace = true }
domain = { workspace = true }
async-trait = { workspace = true }
aws-sdk-s3 = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
aws-config = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
